import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import '@/connection/eagerlyConnect'

import Header from '@/components/molecules/Header'

import Web3Provider from '@/context/web3provider/web3.provider'
import ThemeRegistry from '@/themes/ThemeRegistry'

// const Header = dynamic(() => import('@/components/organisms/header'), {
//   ssr: false,
// })

type RootLayoutProps = {
  children: ReactNode
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <ThemeRegistry>
        <body>
          <Web3Provider>
            <Header />
            {children}
          </Web3Provider>
        </body>
      </ThemeRegistry>
      <body className={inter.className}></body>
    </html>
  )
}
