import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import './globals.css';
import Header from '@/components/organisms/header';

type RootLayoutProps = {
    children: ReactNode;
};

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Header />
                <main>{children}</main>
            </body>
        </html>
    );
}
