/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IKasuControllerAbiInterface extends utils.Interface {
  functions: {
    "checkIsAdminOrVaultAdmin(address,address)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantLendingPoolRole(address,bytes32,address)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasLendingPoolRole(address,bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "requireNotPaused()": FunctionFragment;
    "requirePaused()": FunctionFragment;
    "revokeLendingPoolRole(address,bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "checkIsAdminOrVaultAdmin"
      | "getRoleAdmin"
      | "grantLendingPoolRole"
      | "grantRole"
      | "hasLendingPoolRole"
      | "hasRole"
      | "pause"
      | "paused"
      | "renounceRole"
      | "requireNotPaused"
      | "requirePaused"
      | "revokeLendingPoolRole"
      | "revokeRole"
      | "unpause"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkIsAdminOrVaultAdmin",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantLendingPoolRole",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasLendingPoolRole",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requireNotPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requirePaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeLendingPoolRole",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "checkIsAdminOrVaultAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantLendingPoolRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasLendingPoolRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireNotPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requirePaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeLendingPoolRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "LendingPoolOwnershipGranted(address,address)": EventFragment;
    "LendingPoolRoleGranted(address,bytes32,address)": EventFragment;
    "LendingPoolRoleRenounced(address,bytes32,address)": EventFragment;
    "LendingPoolRoleRevoked(address,bytes32,address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "LendingPoolOwnershipGranted"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LendingPoolRoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LendingPoolRoleRenounced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LendingPoolRoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export interface LendingPoolOwnershipGrantedEventObject {
  lendingPool: string;
  address_: string;
}
export type LendingPoolOwnershipGrantedEvent = TypedEvent<
  [string, string],
  LendingPoolOwnershipGrantedEventObject
>;

export type LendingPoolOwnershipGrantedEventFilter =
  TypedEventFilter<LendingPoolOwnershipGrantedEvent>;

export interface LendingPoolRoleGrantedEventObject {
  lendingPool: string;
  role: string;
  account: string;
}
export type LendingPoolRoleGrantedEvent = TypedEvent<
  [string, string, string],
  LendingPoolRoleGrantedEventObject
>;

export type LendingPoolRoleGrantedEventFilter =
  TypedEventFilter<LendingPoolRoleGrantedEvent>;

export interface LendingPoolRoleRenouncedEventObject {
  lendingPool: string;
  role: string;
  account: string;
}
export type LendingPoolRoleRenouncedEvent = TypedEvent<
  [string, string, string],
  LendingPoolRoleRenouncedEventObject
>;

export type LendingPoolRoleRenouncedEventFilter =
  TypedEventFilter<LendingPoolRoleRenouncedEvent>;

export interface LendingPoolRoleRevokedEventObject {
  lendingPool: string;
  role: string;
  account: string;
}
export type LendingPoolRoleRevokedEvent = TypedEvent<
  [string, string, string],
  LendingPoolRoleRevokedEventObject
>;

export type LendingPoolRoleRevokedEventFilter =
  TypedEventFilter<LendingPoolRoleRevokedEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface IKasuControllerAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IKasuControllerAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    checkIsAdminOrVaultAdmin(
      lendingPool: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    grantLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    hasLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { hasRole: boolean }>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    pause(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    requireNotPaused(overrides?: CallOverrides): Promise<[void]>;

    requirePaused(overrides?: CallOverrides): Promise<[void]>;

    revokeLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  checkIsAdminOrVaultAdmin(
    lendingPool: string,
    account: string,
    overrides?: CallOverrides
  ): Promise<void>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  grantLendingPoolRole(
    lendingPool: string,
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  hasLendingPoolRole(
    lendingPool: string,
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  pause(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  renounceRole(
    role: BytesLike,
    callerConfirmation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  requireNotPaused(overrides?: CallOverrides): Promise<void>;

  requirePaused(overrides?: CallOverrides): Promise<void>;

  revokeLendingPoolRole(
    lendingPool: string,
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    checkIsAdminOrVaultAdmin(
      lendingPool: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    grantLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    requireNotPaused(overrides?: CallOverrides): Promise<void>;

    requirePaused(overrides?: CallOverrides): Promise<void>;

    revokeLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "LendingPoolOwnershipGranted(address,address)"(
      lendingPool?: string | null,
      address_?: string | null
    ): LendingPoolOwnershipGrantedEventFilter;
    LendingPoolOwnershipGranted(
      lendingPool?: string | null,
      address_?: string | null
    ): LendingPoolOwnershipGrantedEventFilter;

    "LendingPoolRoleGranted(address,bytes32,address)"(
      lendingPool?: string | null,
      role?: BytesLike | null,
      account?: string | null
    ): LendingPoolRoleGrantedEventFilter;
    LendingPoolRoleGranted(
      lendingPool?: string | null,
      role?: BytesLike | null,
      account?: string | null
    ): LendingPoolRoleGrantedEventFilter;

    "LendingPoolRoleRenounced(address,bytes32,address)"(
      lendingPool?: string | null,
      role?: BytesLike | null,
      account?: string | null
    ): LendingPoolRoleRenouncedEventFilter;
    LendingPoolRoleRenounced(
      lendingPool?: string | null,
      role?: BytesLike | null,
      account?: string | null
    ): LendingPoolRoleRenouncedEventFilter;

    "LendingPoolRoleRevoked(address,bytes32,address)"(
      lendingPool?: string | null,
      role?: BytesLike | null,
      account?: string | null
    ): LendingPoolRoleRevokedEventFilter;
    LendingPoolRoleRevoked(
      lendingPool?: string | null,
      role?: BytesLike | null,
      account?: string | null
    ): LendingPoolRoleRevokedEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
  };

  estimateGas: {
    checkIsAdminOrVaultAdmin(
      lendingPool: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    hasLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    requireNotPaused(overrides?: CallOverrides): Promise<BigNumber>;

    requirePaused(overrides?: CallOverrides): Promise<BigNumber>;

    revokeLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    unpause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;
  };

  populateTransaction: {
    checkIsAdminOrVaultAdmin(
      lendingPool: string,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    hasLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requireNotPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    requirePaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revokeLendingPoolRole(
      lendingPool: string,
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
