/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type CreateTrancheConfigStruct = {
  ratio: BigNumberish;
  interestRate: BigNumberish;
  minDepositAmount: BigNumberish;
  maxDepositAmount: BigNumberish;
};

export type CreateTrancheConfigStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  ratio: BigNumber;
  interestRate: BigNumber;
  minDepositAmount: BigNumber;
  maxDepositAmount: BigNumber;
};

export type CreatePoolConfigStruct = {
  poolName: string;
  poolSymbol: string;
  targetExcessLiquidityPercentage: BigNumberish;
  tranches: CreateTrancheConfigStruct[];
  poolAdmin: string;
  drawRecipient: string;
  desiredDrawAmount: BigNumberish;
};

export type CreatePoolConfigStructOutput = [
  string,
  string,
  BigNumber,
  CreateTrancheConfigStructOutput[],
  string,
  string,
  BigNumber
] & {
  poolName: string;
  poolSymbol: string;
  targetExcessLiquidityPercentage: BigNumber;
  tranches: CreateTrancheConfigStructOutput[];
  poolAdmin: string;
  drawRecipient: string;
  desiredDrawAmount: BigNumber;
};

export type LendingPoolDeploymentStruct = {
  lendingPool: string;
  pendingPool: string;
  tranches: string[];
};

export type LendingPoolDeploymentStructOutput = [string, string, string[]] & {
  lendingPool: string;
  pendingPool: string;
  tranches: string[];
};

export interface ILendingPoolFactoryAbiInterface extends utils.Interface {
  functions: {
    "createPool((string,string,uint256,(uint256,uint256,uint256,uint256)[],address,address,uint256))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "createPool"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createPool",
    values: [CreatePoolConfigStruct]
  ): string;

  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;

  events: {};
}

export interface ILendingPoolFactoryAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILendingPoolFactoryAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createPool(
      createPoolConfig: CreatePoolConfigStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  createPool(
    createPoolConfig: CreatePoolConfigStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    createPool(
      createPoolConfig: CreatePoolConfigStruct,
      overrides?: CallOverrides
    ): Promise<LendingPoolDeploymentStructOutput>;
  };

  filters: {};

  estimateGas: {
    createPool(
      createPoolConfig: CreatePoolConfigStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createPool(
      createPoolConfig: CreatePoolConfigStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
