/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type ForceWithdrawalInputStruct = {
  tranche: string;
  user: string;
  sharesToWithdraw: BigNumberish;
};

export type ForceWithdrawalInputStructOutput = [string, string, BigNumber] & {
  tranche: string;
  user: string;
  sharesToWithdraw: BigNumber;
};

export type CreateTrancheConfigStruct = {
  ratio: BigNumberish;
  interestRate: BigNumberish;
  minDepositAmount: BigNumberish;
  maxDepositAmount: BigNumberish;
};

export type CreateTrancheConfigStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  ratio: BigNumber;
  interestRate: BigNumber;
  minDepositAmount: BigNumber;
  maxDepositAmount: BigNumber;
};

export type CreatePoolConfigStruct = {
  poolName: string;
  poolSymbol: string;
  targetExcessLiquidityPercentage: BigNumberish;
  minExcessLiquidityPercentage: BigNumberish;
  tranches: CreateTrancheConfigStruct[];
  poolAdmin: string;
  drawRecipient: string;
  desiredDrawAmount: BigNumberish;
};

export type CreatePoolConfigStructOutput = [
  string,
  string,
  BigNumber,
  BigNumber,
  CreateTrancheConfigStructOutput[],
  string,
  string,
  BigNumber
] & {
  poolName: string;
  poolSymbol: string;
  targetExcessLiquidityPercentage: BigNumber;
  minExcessLiquidityPercentage: BigNumber;
  tranches: CreateTrancheConfigStructOutput[];
  poolAdmin: string;
  drawRecipient: string;
  desiredDrawAmount: BigNumber;
};

export type LendingPoolDeploymentStruct = {
  lendingPool: string;
  pendingPool: string;
  tranches: string[];
};

export type LendingPoolDeploymentStructOutput = [string, string, string[]] & {
  lendingPool: string;
  pendingPool: string;
  tranches: string[];
};

export type ClearingConfigurationStruct = {
  drawAmount: BigNumberish;
  trancheDesiredRatios: BigNumberish[];
  maxExcessPercentage: BigNumberish;
  minExcessPercentage: BigNumberish;
};

export type ClearingConfigurationStructOutput = [
  BigNumber,
  BigNumber[],
  BigNumber,
  BigNumber
] & {
  drawAmount: BigNumber;
  trancheDesiredRatios: BigNumber[];
  maxExcessPercentage: BigNumber;
  minExcessPercentage: BigNumber;
};

export type KycDataStruct = {
  blockExpiration: BigNumberish;
  signature: BytesLike;
};

export type KycDataStructOutput = [BigNumber, string] & {
  blockExpiration: BigNumber;
  signature: string;
};

export type LendingPoolWithdrawalConfigurationStruct = {
  requestEpochsInAdvance: BigNumberish;
  cancelRequestEpochsInAdvance: BigNumberish;
};

export type LendingPoolWithdrawalConfigurationStructOutput = [
  BigNumber,
  BigNumber
] & {
  requestEpochsInAdvance: BigNumber;
  cancelRequestEpochsInAdvance: BigNumber;
};

export interface ILendingPoolManagerAbiInterface extends utils.Interface {
  functions: {
    "addLendingPoolTrancheFixedTermDeposit(address,address,uint256,uint256,bool)": FunctionFragment;
    "batchForceWithdrawals(address,(address,address,uint256)[])": FunctionFragment;
    "cancelDepositRequest(address,uint256)": FunctionFragment;
    "cancelFixedTermDepositWithdrawalRequest(address,uint256)": FunctionFragment;
    "cancelWithdrawalRequest(address,uint256)": FunctionFragment;
    "claimRepaidLoss(address,address,uint256)": FunctionFragment;
    "createPool((string,string,uint256,uint256,(uint256,uint256,uint256,uint256)[],address,address,uint256))": FunctionFragment;
    "depositFirstLossCapital(address,uint256)": FunctionFragment;
    "doClearing(address,uint256,uint256,uint256,uint256,(uint256,uint256[],uint256,uint256),bool)": FunctionFragment;
    "endFixedTermDeposit(address,uint256,uint256)": FunctionFragment;
    "forceCancelDepositRequest(address,uint256)": FunctionFragment;
    "forceCancelWithdrawalRequest(address,uint256)": FunctionFragment;
    "forceImmediateWithdrawal(address,address,address,uint256)": FunctionFragment;
    "initialize(address,address,address,address)": FunctionFragment;
    "isLendingPool(address)": FunctionFragment;
    "lendingPools(address)": FunctionFragment;
    "lockDepositForFixedTerm(address,address,uint256,uint256)": FunctionFragment;
    "repayLoss(address,address,uint256,uint256)": FunctionFragment;
    "repayOwedFunds(address,uint256,address)": FunctionFragment;
    "reportLoss(address,uint256,bool)": FunctionFragment;
    "requestDeposit(address,address,uint256,bytes,uint256,bytes)": FunctionFragment;
    "requestDepositWithKyc(address,address,uint256,bytes,uint256,bytes,(uint256,bytes))": FunctionFragment;
    "requestFixedTermDepositWithdrawal(address,uint256)": FunctionFragment;
    "requestWithdrawal(address,address,uint256)": FunctionFragment;
    "stopLendingPool(address)": FunctionFragment;
    "updateDesiredDrawAmount(address,uint256)": FunctionFragment;
    "updateDrawRecipient(address,address)": FunctionFragment;
    "updateFixedTermDepositAllowlist(address,uint256,address[],bool[])": FunctionFragment;
    "updateLendingPoolTrancheFixedInterestStatus(address,uint256,uint8)": FunctionFragment;
    "updateLendingPoolWithdrawalConfiguration(address,(uint128,uint128))": FunctionFragment;
    "updateMaximumDepositAmount(address,address,uint256)": FunctionFragment;
    "updateMinimumDepositAmount(address,address,uint256)": FunctionFragment;
    "updateMinimumExcessLiquidityPercentage(address,uint256)": FunctionFragment;
    "updateTargetExcessLiquidityPercentage(address,uint256)": FunctionFragment;
    "updateTrancheDesiredRatios(address,uint256[])": FunctionFragment;
    "updateTrancheInterestRate(address,address,uint256)": FunctionFragment;
    "updateTrancheInterestRateChangeEpochDelay(address,uint256)": FunctionFragment;
    "withdrawFirstLossCapital(address,uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addLendingPoolTrancheFixedTermDeposit"
      | "batchForceWithdrawals"
      | "cancelDepositRequest"
      | "cancelFixedTermDepositWithdrawalRequest"
      | "cancelWithdrawalRequest"
      | "claimRepaidLoss"
      | "createPool"
      | "depositFirstLossCapital"
      | "doClearing"
      | "endFixedTermDeposit"
      | "forceCancelDepositRequest"
      | "forceCancelWithdrawalRequest"
      | "forceImmediateWithdrawal"
      | "initialize"
      | "isLendingPool"
      | "lendingPools"
      | "lockDepositForFixedTerm"
      | "repayLoss"
      | "repayOwedFunds"
      | "reportLoss"
      | "requestDeposit"
      | "requestDepositWithKyc"
      | "requestFixedTermDepositWithdrawal"
      | "requestWithdrawal"
      | "stopLendingPool"
      | "updateDesiredDrawAmount"
      | "updateDrawRecipient"
      | "updateFixedTermDepositAllowlist"
      | "updateLendingPoolTrancheFixedInterestStatus"
      | "updateLendingPoolWithdrawalConfiguration"
      | "updateMaximumDepositAmount"
      | "updateMinimumDepositAmount"
      | "updateMinimumExcessLiquidityPercentage"
      | "updateTargetExcessLiquidityPercentage"
      | "updateTrancheDesiredRatios"
      | "updateTrancheInterestRate"
      | "updateTrancheInterestRateChangeEpochDelay"
      | "withdrawFirstLossCapital"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addLendingPoolTrancheFixedTermDeposit",
    values: [string, string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "batchForceWithdrawals",
    values: [string, ForceWithdrawalInputStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDepositRequest",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelFixedTermDepositWithdrawalRequest",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelWithdrawalRequest",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRepaidLoss",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [CreatePoolConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFirstLossCapital",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "doClearing",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      ClearingConfigurationStruct,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "endFixedTermDeposit",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceCancelDepositRequest",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceCancelWithdrawalRequest",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceImmediateWithdrawal",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isLendingPool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lendingPools",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lockDepositForFixedTerm",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoss",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayOwedFunds",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "reportLoss",
    values: [string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDeposit",
    values: [string, string, BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDepositWithKyc",
    values: [
      string,
      string,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      KycDataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestFixedTermDepositWithdrawal",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopLendingPool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDesiredDrawAmount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDrawRecipient",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFixedTermDepositAllowlist",
    values: [string, BigNumberish, string[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLendingPoolTrancheFixedInterestStatus",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLendingPoolWithdrawalConfiguration",
    values: [string, LendingPoolWithdrawalConfigurationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaximumDepositAmount",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMinimumDepositAmount",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMinimumExcessLiquidityPercentage",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTargetExcessLiquidityPercentage",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTrancheDesiredRatios",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTrancheInterestRate",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTrancheInterestRateChangeEpochDelay",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFirstLossCapital",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLendingPoolTrancheFixedTermDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchForceWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelDepositRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelFixedTermDepositWithdrawalRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelWithdrawalRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRepaidLoss",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositFirstLossCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doClearing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "endFixedTermDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceCancelDepositRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceCancelWithdrawalRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceImmediateWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lendingPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockDepositForFixedTerm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "repayOwedFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reportLoss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDepositWithKyc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFixedTermDepositWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDesiredDrawAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDrawRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFixedTermDepositAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLendingPoolTrancheFixedInterestStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLendingPoolWithdrawalConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaximumDepositAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMinimumDepositAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMinimumExcessLiquidityPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTargetExcessLiquidityPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTrancheDesiredRatios",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTrancheInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTrancheInterestRateChangeEpochDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFirstLossCapital",
    data: BytesLike
  ): Result;

  events: {
    "DepositDataAdded(address,uint256,bytes)": EventFragment;
    "Initialized(uint64)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositDataAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export interface DepositDataAddedEventObject {
  lendingPool: string;
  dNftID: BigNumber;
  data: string;
}
export type DepositDataAddedEvent = TypedEvent<
  [string, BigNumber, string],
  DepositDataAddedEventObject
>;

export type DepositDataAddedEventFilter =
  TypedEventFilter<DepositDataAddedEvent>;

export interface InitializedEventObject {
  version: BigNumber;
}
export type InitializedEvent = TypedEvent<[BigNumber], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface ILendingPoolManagerAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILendingPoolManagerAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addLendingPoolTrancheFixedTermDeposit(
      lendingPool: string,
      tranche: string,
      epochLockDuration: BigNumberish,
      epochInterestRate: BigNumberish,
      whitelistedOnly: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    batchForceWithdrawals(
      lendingPool: string,
      input: ForceWithdrawalInputStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    cancelDepositRequest(
      lendingPool: string,
      dNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    cancelFixedTermDepositWithdrawalRequest(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    cancelWithdrawalRequest(
      lendingPool: string,
      wNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimRepaidLoss(
      lendingPool: string,
      tranche: string,
      lossId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    createPool(
      createPoolConfig: CreatePoolConfigStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositFirstLossCapital(
      lendingPool: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    doClearing(
      lendingPool: string,
      targetEpoch: BigNumberish,
      fixedTermDepositBatchSize: BigNumberish,
      priorityCalculationBatchSize: BigNumberish,
      acceptRequestsBatchSize: BigNumberish,
      clearingConfigOverride: ClearingConfigurationStruct,
      isConfigOverridden: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    endFixedTermDeposit(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      arrayIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    forceCancelDepositRequest(
      lendingPool: string,
      dNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    forceCancelWithdrawalRequest(
      lendingPool: string,
      wNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    forceImmediateWithdrawal(
      lendingPool: string,
      tranche: string,
      user: string,
      sharesToWithdraw: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    initialize(
      lendingPoolFactory_: string,
      kasuAllowList_: string,
      userManager_: string,
      clearingCoordinator_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isLendingPool(
      lendingPool: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    lendingPools(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string, string] & { lendingPool: string; pendingPool: string }>;

    lockDepositForFixedTerm(
      lendingPool: string,
      tranche: string,
      amount: BigNumberish,
      fixedTermConfigId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    repayLoss(
      lendingPool: string,
      tranche: string,
      lossId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    repayOwedFunds(
      lendingPool: string,
      amount: BigNumberish,
      repaymentAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    reportLoss(
      lendingPool: string,
      amount: BigNumberish,
      doMintLossTokens: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    requestDeposit(
      lendingPool: string,
      tranche: string,
      maxAmount: BigNumberish,
      swapData: BytesLike,
      fixedTermConfigId: BigNumberish,
      depositData: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    requestDepositWithKyc(
      lendingPool: string,
      tranche: string,
      maxAmount: BigNumberish,
      swapData: BytesLike,
      fixedTermConfigId: BigNumberish,
      depositData: BytesLike,
      kycData: KycDataStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    requestFixedTermDepositWithdrawal(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    requestWithdrawal(
      lendingPool: string,
      tranche: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    stopLendingPool(
      lendingPool: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateDesiredDrawAmount(
      lendingPool: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateDrawRecipient(
      lendingPool: string,
      drawRecipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateFixedTermDepositAllowlist(
      lendingPool: string,
      configId: BigNumberish,
      users: string[],
      isAllowedList: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateLendingPoolTrancheFixedInterestStatus(
      lendingPool: string,
      fixedTermConfigId: BigNumberish,
      fixedTermDepositStatus: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateLendingPoolWithdrawalConfiguration(
      lendingPool: string,
      withdrawalConfiguration: LendingPoolWithdrawalConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateMaximumDepositAmount(
      lendingPool: string,
      tranche: string,
      maximumDepositAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateMinimumDepositAmount(
      lendingPool: string,
      tranche: string,
      minimumDepositAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateMinimumExcessLiquidityPercentage(
      lendingPool: string,
      minimumExcessLiquidityPercentage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateTargetExcessLiquidityPercentage(
      lendingPool: string,
      targetExcessLiquidityPercentage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateTrancheDesiredRatios(
      lendingPool: string,
      desiredRatios: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateTrancheInterestRate(
      lendingPool: string,
      tranche: string,
      interestRate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateTrancheInterestRateChangeEpochDelay(
      lendingPool: string,
      epochDelay: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawFirstLossCapital(
      lendingPool: string,
      withdrawAmount: BigNumberish,
      withdrawAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  addLendingPoolTrancheFixedTermDeposit(
    lendingPool: string,
    tranche: string,
    epochLockDuration: BigNumberish,
    epochInterestRate: BigNumberish,
    whitelistedOnly: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  batchForceWithdrawals(
    lendingPool: string,
    input: ForceWithdrawalInputStruct[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  cancelDepositRequest(
    lendingPool: string,
    dNftID: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  cancelFixedTermDepositWithdrawalRequest(
    lendingPool: string,
    fixedTermDepositId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  cancelWithdrawalRequest(
    lendingPool: string,
    wNftID: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimRepaidLoss(
    lendingPool: string,
    tranche: string,
    lossId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  createPool(
    createPoolConfig: CreatePoolConfigStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositFirstLossCapital(
    lendingPool: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  doClearing(
    lendingPool: string,
    targetEpoch: BigNumberish,
    fixedTermDepositBatchSize: BigNumberish,
    priorityCalculationBatchSize: BigNumberish,
    acceptRequestsBatchSize: BigNumberish,
    clearingConfigOverride: ClearingConfigurationStruct,
    isConfigOverridden: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  endFixedTermDeposit(
    lendingPool: string,
    fixedTermDepositId: BigNumberish,
    arrayIndex: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  forceCancelDepositRequest(
    lendingPool: string,
    dNftID: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  forceCancelWithdrawalRequest(
    lendingPool: string,
    wNftID: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  forceImmediateWithdrawal(
    lendingPool: string,
    tranche: string,
    user: string,
    sharesToWithdraw: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  initialize(
    lendingPoolFactory_: string,
    kasuAllowList_: string,
    userManager_: string,
    clearingCoordinator_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isLendingPool(
    lendingPool: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lendingPools(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<[string, string] & { lendingPool: string; pendingPool: string }>;

  lockDepositForFixedTerm(
    lendingPool: string,
    tranche: string,
    amount: BigNumberish,
    fixedTermConfigId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  repayLoss(
    lendingPool: string,
    tranche: string,
    lossId: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  repayOwedFunds(
    lendingPool: string,
    amount: BigNumberish,
    repaymentAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  reportLoss(
    lendingPool: string,
    amount: BigNumberish,
    doMintLossTokens: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  requestDeposit(
    lendingPool: string,
    tranche: string,
    maxAmount: BigNumberish,
    swapData: BytesLike,
    fixedTermConfigId: BigNumberish,
    depositData: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  requestDepositWithKyc(
    lendingPool: string,
    tranche: string,
    maxAmount: BigNumberish,
    swapData: BytesLike,
    fixedTermConfigId: BigNumberish,
    depositData: BytesLike,
    kycData: KycDataStruct,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  requestFixedTermDepositWithdrawal(
    lendingPool: string,
    fixedTermDepositId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  requestWithdrawal(
    lendingPool: string,
    tranche: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  stopLendingPool(
    lendingPool: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateDesiredDrawAmount(
    lendingPool: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateDrawRecipient(
    lendingPool: string,
    drawRecipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateFixedTermDepositAllowlist(
    lendingPool: string,
    configId: BigNumberish,
    users: string[],
    isAllowedList: boolean[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateLendingPoolTrancheFixedInterestStatus(
    lendingPool: string,
    fixedTermConfigId: BigNumberish,
    fixedTermDepositStatus: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateLendingPoolWithdrawalConfiguration(
    lendingPool: string,
    withdrawalConfiguration: LendingPoolWithdrawalConfigurationStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateMaximumDepositAmount(
    lendingPool: string,
    tranche: string,
    maximumDepositAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateMinimumDepositAmount(
    lendingPool: string,
    tranche: string,
    minimumDepositAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateMinimumExcessLiquidityPercentage(
    lendingPool: string,
    minimumExcessLiquidityPercentage: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateTargetExcessLiquidityPercentage(
    lendingPool: string,
    targetExcessLiquidityPercentage: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateTrancheDesiredRatios(
    lendingPool: string,
    desiredRatios: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateTrancheInterestRate(
    lendingPool: string,
    tranche: string,
    interestRate: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateTrancheInterestRateChangeEpochDelay(
    lendingPool: string,
    epochDelay: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawFirstLossCapital(
    lendingPool: string,
    withdrawAmount: BigNumberish,
    withdrawAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    addLendingPoolTrancheFixedTermDeposit(
      lendingPool: string,
      tranche: string,
      epochLockDuration: BigNumberish,
      epochInterestRate: BigNumberish,
      whitelistedOnly: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchForceWithdrawals(
      lendingPool: string,
      input: ForceWithdrawalInputStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    cancelDepositRequest(
      lendingPool: string,
      dNftID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelFixedTermDepositWithdrawalRequest(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelWithdrawalRequest(
      lendingPool: string,
      wNftID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimRepaidLoss(
      lendingPool: string,
      tranche: string,
      lossId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createPool(
      createPoolConfig: CreatePoolConfigStruct,
      overrides?: CallOverrides
    ): Promise<LendingPoolDeploymentStructOutput>;

    depositFirstLossCapital(
      lendingPool: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    doClearing(
      lendingPool: string,
      targetEpoch: BigNumberish,
      fixedTermDepositBatchSize: BigNumberish,
      priorityCalculationBatchSize: BigNumberish,
      acceptRequestsBatchSize: BigNumberish,
      clearingConfigOverride: ClearingConfigurationStruct,
      isConfigOverridden: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    endFixedTermDeposit(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      arrayIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    forceCancelDepositRequest(
      lendingPool: string,
      dNftID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    forceCancelWithdrawalRequest(
      lendingPool: string,
      wNftID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    forceImmediateWithdrawal(
      lendingPool: string,
      tranche: string,
      user: string,
      sharesToWithdraw: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      lendingPoolFactory_: string,
      kasuAllowList_: string,
      userManager_: string,
      clearingCoordinator_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isLendingPool(
      lendingPool: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lendingPools(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string, string] & { lendingPool: string; pendingPool: string }>;

    lockDepositForFixedTerm(
      lendingPool: string,
      tranche: string,
      amount: BigNumberish,
      fixedTermConfigId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    repayLoss(
      lendingPool: string,
      tranche: string,
      lossId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    repayOwedFunds(
      lendingPool: string,
      amount: BigNumberish,
      repaymentAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    reportLoss(
      lendingPool: string,
      amount: BigNumberish,
      doMintLossTokens: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestDeposit(
      lendingPool: string,
      tranche: string,
      maxAmount: BigNumberish,
      swapData: BytesLike,
      fixedTermConfigId: BigNumberish,
      depositData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestDepositWithKyc(
      lendingPool: string,
      tranche: string,
      maxAmount: BigNumberish,
      swapData: BytesLike,
      fixedTermConfigId: BigNumberish,
      depositData: BytesLike,
      kycData: KycDataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestFixedTermDepositWithdrawal(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    requestWithdrawal(
      lendingPool: string,
      tranche: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stopLendingPool(
      lendingPool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDesiredDrawAmount(
      lendingPool: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDrawRecipient(
      lendingPool: string,
      drawRecipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFixedTermDepositAllowlist(
      lendingPool: string,
      configId: BigNumberish,
      users: string[],
      isAllowedList: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    updateLendingPoolTrancheFixedInterestStatus(
      lendingPool: string,
      fixedTermConfigId: BigNumberish,
      fixedTermDepositStatus: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateLendingPoolWithdrawalConfiguration(
      lendingPool: string,
      withdrawalConfiguration: LendingPoolWithdrawalConfigurationStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMaximumDepositAmount(
      lendingPool: string,
      tranche: string,
      maximumDepositAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMinimumDepositAmount(
      lendingPool: string,
      tranche: string,
      minimumDepositAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMinimumExcessLiquidityPercentage(
      lendingPool: string,
      minimumExcessLiquidityPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTargetExcessLiquidityPercentage(
      lendingPool: string,
      targetExcessLiquidityPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTrancheDesiredRatios(
      lendingPool: string,
      desiredRatios: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    updateTrancheInterestRate(
      lendingPool: string,
      tranche: string,
      interestRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTrancheInterestRateChangeEpochDelay(
      lendingPool: string,
      epochDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFirstLossCapital(
      lendingPool: string,
      withdrawAmount: BigNumberish,
      withdrawAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DepositDataAdded(address,uint256,bytes)"(
      lendingPool?: string | null,
      dNftID?: BigNumberish | null,
      data?: null
    ): DepositDataAddedEventFilter;
    DepositDataAdded(
      lendingPool?: string | null,
      dNftID?: BigNumberish | null,
      data?: null
    ): DepositDataAddedEventFilter;

    "Initialized(uint64)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;
  };

  estimateGas: {
    addLendingPoolTrancheFixedTermDeposit(
      lendingPool: string,
      tranche: string,
      epochLockDuration: BigNumberish,
      epochInterestRate: BigNumberish,
      whitelistedOnly: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    batchForceWithdrawals(
      lendingPool: string,
      input: ForceWithdrawalInputStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    cancelDepositRequest(
      lendingPool: string,
      dNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    cancelFixedTermDepositWithdrawalRequest(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    cancelWithdrawalRequest(
      lendingPool: string,
      wNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claimRepaidLoss(
      lendingPool: string,
      tranche: string,
      lossId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    createPool(
      createPoolConfig: CreatePoolConfigStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositFirstLossCapital(
      lendingPool: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    doClearing(
      lendingPool: string,
      targetEpoch: BigNumberish,
      fixedTermDepositBatchSize: BigNumberish,
      priorityCalculationBatchSize: BigNumberish,
      acceptRequestsBatchSize: BigNumberish,
      clearingConfigOverride: ClearingConfigurationStruct,
      isConfigOverridden: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    endFixedTermDeposit(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      arrayIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    forceCancelDepositRequest(
      lendingPool: string,
      dNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    forceCancelWithdrawalRequest(
      lendingPool: string,
      wNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    forceImmediateWithdrawal(
      lendingPool: string,
      tranche: string,
      user: string,
      sharesToWithdraw: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    initialize(
      lendingPoolFactory_: string,
      kasuAllowList_: string,
      userManager_: string,
      clearingCoordinator_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isLendingPool(
      lendingPool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lendingPools(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    lockDepositForFixedTerm(
      lendingPool: string,
      tranche: string,
      amount: BigNumberish,
      fixedTermConfigId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    repayLoss(
      lendingPool: string,
      tranche: string,
      lossId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    repayOwedFunds(
      lendingPool: string,
      amount: BigNumberish,
      repaymentAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    reportLoss(
      lendingPool: string,
      amount: BigNumberish,
      doMintLossTokens: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    requestDeposit(
      lendingPool: string,
      tranche: string,
      maxAmount: BigNumberish,
      swapData: BytesLike,
      fixedTermConfigId: BigNumberish,
      depositData: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    requestDepositWithKyc(
      lendingPool: string,
      tranche: string,
      maxAmount: BigNumberish,
      swapData: BytesLike,
      fixedTermConfigId: BigNumberish,
      depositData: BytesLike,
      kycData: KycDataStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    requestFixedTermDepositWithdrawal(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    requestWithdrawal(
      lendingPool: string,
      tranche: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    stopLendingPool(
      lendingPool: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateDesiredDrawAmount(
      lendingPool: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateDrawRecipient(
      lendingPool: string,
      drawRecipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateFixedTermDepositAllowlist(
      lendingPool: string,
      configId: BigNumberish,
      users: string[],
      isAllowedList: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateLendingPoolTrancheFixedInterestStatus(
      lendingPool: string,
      fixedTermConfigId: BigNumberish,
      fixedTermDepositStatus: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateLendingPoolWithdrawalConfiguration(
      lendingPool: string,
      withdrawalConfiguration: LendingPoolWithdrawalConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateMaximumDepositAmount(
      lendingPool: string,
      tranche: string,
      maximumDepositAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateMinimumDepositAmount(
      lendingPool: string,
      tranche: string,
      minimumDepositAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateMinimumExcessLiquidityPercentage(
      lendingPool: string,
      minimumExcessLiquidityPercentage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateTargetExcessLiquidityPercentage(
      lendingPool: string,
      targetExcessLiquidityPercentage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateTrancheDesiredRatios(
      lendingPool: string,
      desiredRatios: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateTrancheInterestRate(
      lendingPool: string,
      tranche: string,
      interestRate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateTrancheInterestRateChangeEpochDelay(
      lendingPool: string,
      epochDelay: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawFirstLossCapital(
      lendingPool: string,
      withdrawAmount: BigNumberish,
      withdrawAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addLendingPoolTrancheFixedTermDeposit(
      lendingPool: string,
      tranche: string,
      epochLockDuration: BigNumberish,
      epochInterestRate: BigNumberish,
      whitelistedOnly: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    batchForceWithdrawals(
      lendingPool: string,
      input: ForceWithdrawalInputStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    cancelDepositRequest(
      lendingPool: string,
      dNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    cancelFixedTermDepositWithdrawalRequest(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    cancelWithdrawalRequest(
      lendingPool: string,
      wNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimRepaidLoss(
      lendingPool: string,
      tranche: string,
      lossId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    createPool(
      createPoolConfig: CreatePoolConfigStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositFirstLossCapital(
      lendingPool: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    doClearing(
      lendingPool: string,
      targetEpoch: BigNumberish,
      fixedTermDepositBatchSize: BigNumberish,
      priorityCalculationBatchSize: BigNumberish,
      acceptRequestsBatchSize: BigNumberish,
      clearingConfigOverride: ClearingConfigurationStruct,
      isConfigOverridden: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    endFixedTermDeposit(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      arrayIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    forceCancelDepositRequest(
      lendingPool: string,
      dNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    forceCancelWithdrawalRequest(
      lendingPool: string,
      wNftID: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    forceImmediateWithdrawal(
      lendingPool: string,
      tranche: string,
      user: string,
      sharesToWithdraw: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    initialize(
      lendingPoolFactory_: string,
      kasuAllowList_: string,
      userManager_: string,
      clearingCoordinator_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isLendingPool(
      lendingPool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lendingPools(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockDepositForFixedTerm(
      lendingPool: string,
      tranche: string,
      amount: BigNumberish,
      fixedTermConfigId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    repayLoss(
      lendingPool: string,
      tranche: string,
      lossId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    repayOwedFunds(
      lendingPool: string,
      amount: BigNumberish,
      repaymentAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    reportLoss(
      lendingPool: string,
      amount: BigNumberish,
      doMintLossTokens: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requestDeposit(
      lendingPool: string,
      tranche: string,
      maxAmount: BigNumberish,
      swapData: BytesLike,
      fixedTermConfigId: BigNumberish,
      depositData: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requestDepositWithKyc(
      lendingPool: string,
      tranche: string,
      maxAmount: BigNumberish,
      swapData: BytesLike,
      fixedTermConfigId: BigNumberish,
      depositData: BytesLike,
      kycData: KycDataStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requestFixedTermDepositWithdrawal(
      lendingPool: string,
      fixedTermDepositId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requestWithdrawal(
      lendingPool: string,
      tranche: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    stopLendingPool(
      lendingPool: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateDesiredDrawAmount(
      lendingPool: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateDrawRecipient(
      lendingPool: string,
      drawRecipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateFixedTermDepositAllowlist(
      lendingPool: string,
      configId: BigNumberish,
      users: string[],
      isAllowedList: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateLendingPoolTrancheFixedInterestStatus(
      lendingPool: string,
      fixedTermConfigId: BigNumberish,
      fixedTermDepositStatus: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateLendingPoolWithdrawalConfiguration(
      lendingPool: string,
      withdrawalConfiguration: LendingPoolWithdrawalConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateMaximumDepositAmount(
      lendingPool: string,
      tranche: string,
      maximumDepositAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateMinimumDepositAmount(
      lendingPool: string,
      tranche: string,
      minimumDepositAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateMinimumExcessLiquidityPercentage(
      lendingPool: string,
      minimumExcessLiquidityPercentage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateTargetExcessLiquidityPercentage(
      lendingPool: string,
      targetExcessLiquidityPercentage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateTrancheDesiredRatios(
      lendingPool: string,
      desiredRatios: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateTrancheInterestRate(
      lendingPool: string,
      tranche: string,
      interestRate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateTrancheInterestRateChangeEpochDelay(
      lendingPool: string,
      epochDelay: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawFirstLossCapital(
      lendingPool: string,
      withdrawAmount: BigNumberish,
      withdrawAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
