/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type TrancheInfoStruct = { trancheName: string; tokenSymbol: string };

export type TrancheInfoStructOutput = [string, string] & {
  trancheName: string;
  tokenSymbol: string;
};

export interface ISystemVariablesAbiInterface extends utils.Interface {
  functions: {
    "clearingPeriodLength()": FunctionFragment;
    "currentEpochNumber()": FunctionFragment;
    "currentRequestEpoch()": FunctionFragment;
    "defaultTrancheInterestChangeEpochDelay()": FunctionFragment;
    "epochDuration()": FunctionFragment;
    "epochStartTimestamp(uint256)": FunctionFragment;
    "feeRates()": FunctionFragment;
    "isClearingTime()": FunctionFragment;
    "ksuEpochTokenPrice()": FunctionFragment;
    "loyaltyLevelsCount()": FunctionFragment;
    "loyaltyThresholds()": FunctionFragment;
    "maxTrancheCountPerLendingPool()": FunctionFragment;
    "maxTrancheInterestRate()": FunctionFragment;
    "minTrancheCountPerLendingPool()": FunctionFragment;
    "nextEpochStartTimestamp()": FunctionFragment;
    "performanceFee()": FunctionFragment;
    "priceUpdateEpoch()": FunctionFragment;
    "protocolFeeReceiver()": FunctionFragment;
    "setDefaultTrancheInterestChangeEpochDelay(uint256)": FunctionFragment;
    "setFeeRates(uint256,uint256)": FunctionFragment;
    "setLoyaltyThresholds(uint256[])": FunctionFragment;
    "setMaxTrancheInterestRate(uint256)": FunctionFragment;
    "setPerformanceFee(uint256)": FunctionFragment;
    "setProtocolFeeReceiver(address)": FunctionFragment;
    "setUserCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(bool)": FunctionFragment;
    "trancheNameInfo(uint256)": FunctionFragment;
    "updateKsuEpochTokenPrice()": FunctionFragment;
    "userCanOnlyDepositToJuniorTrancheWhenHeHasRKSU()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "clearingPeriodLength"
      | "currentEpochNumber"
      | "currentRequestEpoch"
      | "defaultTrancheInterestChangeEpochDelay"
      | "epochDuration"
      | "epochStartTimestamp"
      | "feeRates"
      | "isClearingTime"
      | "ksuEpochTokenPrice"
      | "loyaltyLevelsCount"
      | "loyaltyThresholds"
      | "maxTrancheCountPerLendingPool"
      | "maxTrancheInterestRate"
      | "minTrancheCountPerLendingPool"
      | "nextEpochStartTimestamp"
      | "performanceFee"
      | "priceUpdateEpoch"
      | "protocolFeeReceiver"
      | "setDefaultTrancheInterestChangeEpochDelay"
      | "setFeeRates"
      | "setLoyaltyThresholds"
      | "setMaxTrancheInterestRate"
      | "setPerformanceFee"
      | "setProtocolFeeReceiver"
      | "setUserCanOnlyDepositToJuniorTrancheWhenHeHasRKSU"
      | "trancheNameInfo"
      | "updateKsuEpochTokenPrice"
      | "userCanOnlyDepositToJuniorTrancheWhenHeHasRKSU"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "clearingPeriodLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentEpochNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentRequestEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultTrancheInterestChangeEpochDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochStartTimestamp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeRates", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isClearingTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ksuEpochTokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "loyaltyLevelsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "loyaltyThresholds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTrancheCountPerLendingPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTrancheInterestRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTrancheCountPerLendingPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextEpochStartTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "performanceFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceUpdateEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultTrancheInterestChangeEpochDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRates",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLoyaltyThresholds",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxTrancheInterestRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPerformanceFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeReceiver",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserCanOnlyDepositToJuniorTrancheWhenHeHasRKSU",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "trancheNameInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateKsuEpochTokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userCanOnlyDepositToJuniorTrancheWhenHeHasRKSU",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "clearingPeriodLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentEpochNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRequestEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultTrancheInterestChangeEpochDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochStartTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeRates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isClearingTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ksuEpochTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loyaltyLevelsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loyaltyThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTrancheCountPerLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTrancheInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTrancheCountPerLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEpochStartTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performanceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceUpdateEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultTrancheInterestChangeEpochDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLoyaltyThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTrancheInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPerformanceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserCanOnlyDepositToJuniorTrancheWhenHeHasRKSU",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trancheNameInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateKsuEpochTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCanOnlyDepositToJuniorTrancheWhenHeHasRKSU",
    data: BytesLike
  ): Result;

  events: {
    "KsuTokenPriceUpdated(uint256,uint256)": EventFragment;
    "PerformanceFeeUpdated(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "KsuTokenPriceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PerformanceFeeUpdated"): EventFragment;
}

export interface KsuTokenPriceUpdatedEventObject {
  epoch: BigNumber;
  ksuTokenPrice: BigNumber;
}
export type KsuTokenPriceUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  KsuTokenPriceUpdatedEventObject
>;

export type KsuTokenPriceUpdatedEventFilter =
  TypedEventFilter<KsuTokenPriceUpdatedEvent>;

export interface PerformanceFeeUpdatedEventObject {
  performanceFee: BigNumber;
}
export type PerformanceFeeUpdatedEvent = TypedEvent<
  [BigNumber],
  PerformanceFeeUpdatedEventObject
>;

export type PerformanceFeeUpdatedEventFilter =
  TypedEventFilter<PerformanceFeeUpdatedEvent>;

export interface ISystemVariablesAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISystemVariablesAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    clearingPeriodLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    currentEpochNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    currentRequestEpoch(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { requestEpoch: BigNumber }>;

    defaultTrancheInterestChangeEpochDelay(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    epochDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    epochStartTimestamp(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    feeRates(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        ecosystemFeeRate: BigNumber;
        protocolFeeRate: BigNumber;
      }
    >;

    isClearingTime(overrides?: CallOverrides): Promise<[boolean]>;

    ksuEpochTokenPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    loyaltyLevelsCount(overrides?: CallOverrides): Promise<[number]>;

    loyaltyThresholds(
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { loyaltyThresholds: BigNumber[] }>;

    maxTrancheCountPerLendingPool(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxTrancheInterestRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    minTrancheCountPerLendingPool(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    nextEpochStartTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    performanceFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    priceUpdateEpoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    protocolFeeReceiver(overrides?: CallOverrides): Promise<[string]>;

    setDefaultTrancheInterestChangeEpochDelay(
      defaultTrancheInterestChangeEpochDelay_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setFeeRates(
      ecosystemFeeRate: BigNumberish,
      protocolFeeRate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setLoyaltyThresholds(
      loyaltyThresholds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setMaxTrancheInterestRate(
      maxTrancheInterestRate_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setPerformanceFee(
      performanceFee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setProtocolFeeReceiver(
      receiver: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setUserCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
      value: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    trancheNameInfo(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[TrancheInfoStructOutput]>;

    updateKsuEpochTokenPrice(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    userCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  clearingPeriodLength(overrides?: CallOverrides): Promise<BigNumber>;

  currentEpochNumber(overrides?: CallOverrides): Promise<BigNumber>;

  currentRequestEpoch(overrides?: CallOverrides): Promise<BigNumber>;

  defaultTrancheInterestChangeEpochDelay(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  epochDuration(overrides?: CallOverrides): Promise<BigNumber>;

  epochStartTimestamp(
    epoch: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  feeRates(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      ecosystemFeeRate: BigNumber;
      protocolFeeRate: BigNumber;
    }
  >;

  isClearingTime(overrides?: CallOverrides): Promise<boolean>;

  ksuEpochTokenPrice(overrides?: CallOverrides): Promise<BigNumber>;

  loyaltyLevelsCount(overrides?: CallOverrides): Promise<number>;

  loyaltyThresholds(overrides?: CallOverrides): Promise<BigNumber[]>;

  maxTrancheCountPerLendingPool(overrides?: CallOverrides): Promise<BigNumber>;

  maxTrancheInterestRate(overrides?: CallOverrides): Promise<BigNumber>;

  minTrancheCountPerLendingPool(overrides?: CallOverrides): Promise<BigNumber>;

  nextEpochStartTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  performanceFee(overrides?: CallOverrides): Promise<BigNumber>;

  priceUpdateEpoch(overrides?: CallOverrides): Promise<BigNumber>;

  protocolFeeReceiver(overrides?: CallOverrides): Promise<string>;

  setDefaultTrancheInterestChangeEpochDelay(
    defaultTrancheInterestChangeEpochDelay_: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setFeeRates(
    ecosystemFeeRate: BigNumberish,
    protocolFeeRate: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setLoyaltyThresholds(
    loyaltyThresholds: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setMaxTrancheInterestRate(
    maxTrancheInterestRate_: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setPerformanceFee(
    performanceFee: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setProtocolFeeReceiver(
    receiver: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setUserCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
    value: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  trancheNameInfo(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<TrancheInfoStructOutput>;

  updateKsuEpochTokenPrice(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  userCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    clearingPeriodLength(overrides?: CallOverrides): Promise<BigNumber>;

    currentEpochNumber(overrides?: CallOverrides): Promise<BigNumber>;

    currentRequestEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    defaultTrancheInterestChangeEpochDelay(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    epochDuration(overrides?: CallOverrides): Promise<BigNumber>;

    epochStartTimestamp(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feeRates(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        ecosystemFeeRate: BigNumber;
        protocolFeeRate: BigNumber;
      }
    >;

    isClearingTime(overrides?: CallOverrides): Promise<boolean>;

    ksuEpochTokenPrice(overrides?: CallOverrides): Promise<BigNumber>;

    loyaltyLevelsCount(overrides?: CallOverrides): Promise<number>;

    loyaltyThresholds(overrides?: CallOverrides): Promise<BigNumber[]>;

    maxTrancheCountPerLendingPool(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxTrancheInterestRate(overrides?: CallOverrides): Promise<BigNumber>;

    minTrancheCountPerLendingPool(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextEpochStartTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    performanceFee(overrides?: CallOverrides): Promise<BigNumber>;

    priceUpdateEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeReceiver(overrides?: CallOverrides): Promise<string>;

    setDefaultTrancheInterestChangeEpochDelay(
      defaultTrancheInterestChangeEpochDelay_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeRates(
      ecosystemFeeRate: BigNumberish,
      protocolFeeRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setLoyaltyThresholds(
      loyaltyThresholds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxTrancheInterestRate(
      maxTrancheInterestRate_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPerformanceFee(
      performanceFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFeeReceiver(
      receiver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setUserCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
      value: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    trancheNameInfo(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<TrancheInfoStructOutput>;

    updateKsuEpochTokenPrice(overrides?: CallOverrides): Promise<void>;

    userCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "KsuTokenPriceUpdated(uint256,uint256)"(
      epoch?: BigNumberish | null,
      ksuTokenPrice?: null
    ): KsuTokenPriceUpdatedEventFilter;
    KsuTokenPriceUpdated(
      epoch?: BigNumberish | null,
      ksuTokenPrice?: null
    ): KsuTokenPriceUpdatedEventFilter;

    "PerformanceFeeUpdated(uint256)"(
      performanceFee?: null
    ): PerformanceFeeUpdatedEventFilter;
    PerformanceFeeUpdated(
      performanceFee?: null
    ): PerformanceFeeUpdatedEventFilter;
  };

  estimateGas: {
    clearingPeriodLength(overrides?: CallOverrides): Promise<BigNumber>;

    currentEpochNumber(overrides?: CallOverrides): Promise<BigNumber>;

    currentRequestEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    defaultTrancheInterestChangeEpochDelay(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    epochDuration(overrides?: CallOverrides): Promise<BigNumber>;

    epochStartTimestamp(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    feeRates(overrides?: CallOverrides): Promise<BigNumber>;

    isClearingTime(overrides?: CallOverrides): Promise<BigNumber>;

    ksuEpochTokenPrice(overrides?: CallOverrides): Promise<BigNumber>;

    loyaltyLevelsCount(overrides?: CallOverrides): Promise<BigNumber>;

    loyaltyThresholds(overrides?: CallOverrides): Promise<BigNumber>;

    maxTrancheCountPerLendingPool(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxTrancheInterestRate(overrides?: CallOverrides): Promise<BigNumber>;

    minTrancheCountPerLendingPool(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextEpochStartTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    performanceFee(overrides?: CallOverrides): Promise<BigNumber>;

    priceUpdateEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeReceiver(overrides?: CallOverrides): Promise<BigNumber>;

    setDefaultTrancheInterestChangeEpochDelay(
      defaultTrancheInterestChangeEpochDelay_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setFeeRates(
      ecosystemFeeRate: BigNumberish,
      protocolFeeRate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setLoyaltyThresholds(
      loyaltyThresholds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setMaxTrancheInterestRate(
      maxTrancheInterestRate_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setPerformanceFee(
      performanceFee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setProtocolFeeReceiver(
      receiver: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setUserCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
      value: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    trancheNameInfo(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateKsuEpochTokenPrice(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    userCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    clearingPeriodLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentEpochNumber(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentRequestEpoch(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    defaultTrancheInterestChangeEpochDelay(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    epochDuration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochStartTimestamp(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feeRates(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isClearingTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ksuEpochTokenPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    loyaltyLevelsCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    loyaltyThresholds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxTrancheCountPerLendingPool(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxTrancheInterestRate(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minTrancheCountPerLendingPool(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextEpochStartTimestamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    performanceFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceUpdateEpoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeReceiver(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setDefaultTrancheInterestChangeEpochDelay(
      defaultTrancheInterestChangeEpochDelay_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setFeeRates(
      ecosystemFeeRate: BigNumberish,
      protocolFeeRate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setLoyaltyThresholds(
      loyaltyThresholds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setMaxTrancheInterestRate(
      maxTrancheInterestRate_: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setPerformanceFee(
      performanceFee: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setProtocolFeeReceiver(
      receiver: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setUserCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
      value: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    trancheNameInfo(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateKsuEpochTokenPrice(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    userCanOnlyDepositToJuniorTrancheWhenHeHasRKSU(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
