/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type EpochUserLoyaltyProcessingStruct = {
  didStart: boolean;
  userCount: BigNumberish;
  processedUsersCount: BigNumberish;
};

export type EpochUserLoyaltyProcessingStructOutput = [
  boolean,
  BigNumber,
  BigNumber
] & { didStart: boolean; userCount: BigNumber; processedUsersCount: BigNumber };

export interface IUserManagerAbiInterface extends utils.Interface {
  functions: {
    "allUsers()": FunctionFragment;
    "areUserEpochLoyaltyLevelProcessed(uint256)": FunctionFragment;
    "batchCalculateUserLoyaltyLevels(uint256)": FunctionFragment;
    "calculatedUserEpochLoyaltyLevel(address,uint256)": FunctionFragment;
    "canUserDepositInJuniorTranche(address)": FunctionFragment;
    "epochUserLoyaltyProcessing(uint256)": FunctionFragment;
    "hasUserRKSU(address)": FunctionFragment;
    "updateUserLendingPools(uint256,uint256)": FunctionFragment;
    "userLendingPools(address)": FunctionFragment;
    "userLoyaltyLevel(address)": FunctionFragment;
    "userRequestedDeposit(address,address)": FunctionFragment;
    "userTotalPendingAndActiveDepositedAmount(address)": FunctionFragment;
    "userTotalPendingAndActiveDepositedAmountForCurrentEpoch(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allUsers"
      | "areUserEpochLoyaltyLevelProcessed"
      | "batchCalculateUserLoyaltyLevels"
      | "calculatedUserEpochLoyaltyLevel"
      | "canUserDepositInJuniorTranche"
      | "epochUserLoyaltyProcessing"
      | "hasUserRKSU"
      | "updateUserLendingPools"
      | "userLendingPools"
      | "userLoyaltyLevel"
      | "userRequestedDeposit"
      | "userTotalPendingAndActiveDepositedAmount"
      | "userTotalPendingAndActiveDepositedAmountForCurrentEpoch"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "allUsers", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "areUserEpochLoyaltyLevelProcessed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCalculateUserLoyaltyLevels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatedUserEpochLoyaltyLevel",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canUserDepositInJuniorTranche",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "epochUserLoyaltyProcessing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hasUserRKSU", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateUserLendingPools",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userLendingPools",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userLoyaltyLevel",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userRequestedDeposit",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalPendingAndActiveDepositedAmount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalPendingAndActiveDepositedAmountForCurrentEpoch",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "allUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "areUserEpochLoyaltyLevelProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCalculateUserLoyaltyLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatedUserEpochLoyaltyLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canUserDepositInJuniorTranche",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochUserLoyaltyProcessing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserRKSU",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUserLendingPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userLendingPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userLoyaltyLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRequestedDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTotalPendingAndActiveDepositedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTotalPendingAndActiveDepositedAmountForCurrentEpoch",
    data: BytesLike
  ): Result;

  events: {
    "UserLoyaltyLevelUpdated(address,uint256,uint256)": EventFragment;
    "UserLoyaltyLevelsForEpochProcessed(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "UserLoyaltyLevelUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "UserLoyaltyLevelsForEpochProcessed"
  ): EventFragment;
}

export interface UserLoyaltyLevelUpdatedEventObject {
  user: string;
  epoch: BigNumber;
  loyaltyLevel: BigNumber;
}
export type UserLoyaltyLevelUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  UserLoyaltyLevelUpdatedEventObject
>;

export type UserLoyaltyLevelUpdatedEventFilter =
  TypedEventFilter<UserLoyaltyLevelUpdatedEvent>;

export interface UserLoyaltyLevelsForEpochProcessedEventObject {
  epoch: BigNumber;
  userCount: BigNumber;
}
export type UserLoyaltyLevelsForEpochProcessedEvent = TypedEvent<
  [BigNumber, BigNumber],
  UserLoyaltyLevelsForEpochProcessedEventObject
>;

export type UserLoyaltyLevelsForEpochProcessedEventFilter =
  TypedEventFilter<UserLoyaltyLevelsForEpochProcessedEvent>;

export interface IUserManagerAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IUserManagerAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allUsers(overrides?: CallOverrides): Promise<[string[]]>;

    areUserEpochLoyaltyLevelProcessed(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    batchCalculateUserLoyaltyLevels(
      batchSize: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    calculatedUserEpochLoyaltyLevel(
      user: string,
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number] & { loyaltyLevel: number }>;

    canUserDepositInJuniorTranche(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    epochUserLoyaltyProcessing(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[EpochUserLoyaltyProcessingStructOutput]>;

    hasUserRKSU(user: string, overrides?: CallOverrides): Promise<[boolean]>;

    updateUserLendingPools(
      fromIndex: BigNumberish,
      toIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    userLendingPools(
      user: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    userLoyaltyLevel(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & { currentEpoch: BigNumber; loyaltyLevel: number }
    >;

    userRequestedDeposit(
      user: string,
      lendingPool: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    userTotalPendingAndActiveDepositedAmount(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        activeDepositAmount: BigNumber;
        pendingDepositAmount: BigNumber;
      }
    >;

    userTotalPendingAndActiveDepositedAmountForCurrentEpoch(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        activeDepositAmount: BigNumber;
        pendingDepositAmount: BigNumber;
      }
    >;
  };

  allUsers(overrides?: CallOverrides): Promise<string[]>;

  areUserEpochLoyaltyLevelProcessed(
    epoch: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  batchCalculateUserLoyaltyLevels(
    batchSize: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  calculatedUserEpochLoyaltyLevel(
    user: string,
    epoch: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  canUserDepositInJuniorTranche(
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  epochUserLoyaltyProcessing(
    epoch: BigNumberish,
    overrides?: CallOverrides
  ): Promise<EpochUserLoyaltyProcessingStructOutput>;

  hasUserRKSU(user: string, overrides?: CallOverrides): Promise<boolean>;

  updateUserLendingPools(
    fromIndex: BigNumberish,
    toIndex: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  userLendingPools(
    user: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  userLoyaltyLevel(
    user: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number] & { currentEpoch: BigNumber; loyaltyLevel: number }
  >;

  userRequestedDeposit(
    user: string,
    lendingPool: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  userTotalPendingAndActiveDepositedAmount(
    user: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      activeDepositAmount: BigNumber;
      pendingDepositAmount: BigNumber;
    }
  >;

  userTotalPendingAndActiveDepositedAmountForCurrentEpoch(
    user: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      activeDepositAmount: BigNumber;
      pendingDepositAmount: BigNumber;
    }
  >;

  callStatic: {
    allUsers(overrides?: CallOverrides): Promise<string[]>;

    areUserEpochLoyaltyLevelProcessed(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    batchCalculateUserLoyaltyLevels(
      batchSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    calculatedUserEpochLoyaltyLevel(
      user: string,
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    canUserDepositInJuniorTranche(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    epochUserLoyaltyProcessing(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<EpochUserLoyaltyProcessingStructOutput>;

    hasUserRKSU(user: string, overrides?: CallOverrides): Promise<boolean>;

    updateUserLendingPools(
      fromIndex: BigNumberish,
      toIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    userLendingPools(
      user: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    userLoyaltyLevel(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & { currentEpoch: BigNumber; loyaltyLevel: number }
    >;

    userRequestedDeposit(
      user: string,
      lendingPool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userTotalPendingAndActiveDepositedAmount(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        activeDepositAmount: BigNumber;
        pendingDepositAmount: BigNumber;
      }
    >;

    userTotalPendingAndActiveDepositedAmountForCurrentEpoch(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        activeDepositAmount: BigNumber;
        pendingDepositAmount: BigNumber;
      }
    >;
  };

  filters: {
    "UserLoyaltyLevelUpdated(address,uint256,uint256)"(
      user?: string | null,
      epoch?: BigNumberish | null,
      loyaltyLevel?: null
    ): UserLoyaltyLevelUpdatedEventFilter;
    UserLoyaltyLevelUpdated(
      user?: string | null,
      epoch?: BigNumberish | null,
      loyaltyLevel?: null
    ): UserLoyaltyLevelUpdatedEventFilter;

    "UserLoyaltyLevelsForEpochProcessed(uint256,uint256)"(
      epoch?: BigNumberish | null,
      userCount?: null
    ): UserLoyaltyLevelsForEpochProcessedEventFilter;
    UserLoyaltyLevelsForEpochProcessed(
      epoch?: BigNumberish | null,
      userCount?: null
    ): UserLoyaltyLevelsForEpochProcessedEventFilter;
  };

  estimateGas: {
    allUsers(overrides?: CallOverrides): Promise<BigNumber>;

    areUserEpochLoyaltyLevelProcessed(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchCalculateUserLoyaltyLevels(
      batchSize: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    calculatedUserEpochLoyaltyLevel(
      user: string,
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canUserDepositInJuniorTranche(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    epochUserLoyaltyProcessing(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasUserRKSU(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    updateUserLendingPools(
      fromIndex: BigNumberish,
      toIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    userLendingPools(
      user: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    userLoyaltyLevel(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userRequestedDeposit(
      user: string,
      lendingPool: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    userTotalPendingAndActiveDepositedAmount(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userTotalPendingAndActiveDepositedAmountForCurrentEpoch(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allUsers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    areUserEpochLoyaltyLevelProcessed(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchCalculateUserLoyaltyLevels(
      batchSize: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    calculatedUserEpochLoyaltyLevel(
      user: string,
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canUserDepositInJuniorTranche(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    epochUserLoyaltyProcessing(
      epoch: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasUserRKSU(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateUserLendingPools(
      fromIndex: BigNumberish,
      toIndex: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    userLendingPools(
      user: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    userLoyaltyLevel(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userRequestedDeposit(
      user: string,
      lendingPool: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    userTotalPendingAndActiveDepositedAmount(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userTotalPendingAndActiveDepositedAmountForCurrentEpoch(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
