/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type UserRewardInputStruct = {
  user: string;
  epoch: BigNumberish;
  userLoyaltyLevel: BigNumberish;
  amountDeposited: BigNumberish;
};

export type UserRewardInputStructOutput = [
  string,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  user: string;
  epoch: BigNumber;
  userLoyaltyLevel: BigNumber;
  amountDeposited: BigNumber;
};

export type LoyaltyEpochRewardRateInputStruct = {
  loyaltyLevel: BigNumberish;
  epochRewardRate: BigNumberish;
};

export type LoyaltyEpochRewardRateInputStructOutput = [BigNumber, BigNumber] & {
  loyaltyLevel: BigNumber;
  epochRewardRate: BigNumber;
};

export interface IUserLoyaltyRewardsAbiInterface extends utils.Interface {
  functions: {
    "claimReward(uint256)": FunctionFragment;
    "doEmitRewards()": FunctionFragment;
    "emitUserLoyaltyReward(address,uint256,uint256,uint256)": FunctionFragment;
    "emitUserLoyaltyRewardBatch((address,uint256,uint256,uint256)[],uint256)": FunctionFragment;
    "loyaltyEpochRewardRates(uint256)": FunctionFragment;
    "recoverERC20(address,uint256,address)": FunctionFragment;
    "setDoEmitRewards(bool)": FunctionFragment;
    "setRewardRatesPerLoyaltyLevel((uint256,uint256)[])": FunctionFragment;
    "totalUnclaimedRewards()": FunctionFragment;
    "userRewards(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claimReward"
      | "doEmitRewards"
      | "emitUserLoyaltyReward"
      | "emitUserLoyaltyRewardBatch"
      | "loyaltyEpochRewardRates"
      | "recoverERC20"
      | "setDoEmitRewards"
      | "setRewardRatesPerLoyaltyLevel"
      | "totalUnclaimedRewards"
      | "userRewards"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "doEmitRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emitUserLoyaltyReward",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitUserLoyaltyRewardBatch",
    values: [UserRewardInputStruct[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loyaltyEpochRewardRates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDoEmitRewards",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardRatesPerLoyaltyLevel",
    values: [LoyaltyEpochRewardRateInputStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "totalUnclaimedRewards",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "userRewards", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doEmitRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitUserLoyaltyReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitUserLoyaltyRewardBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loyaltyEpochRewardRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDoEmitRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardRatesPerLoyaltyLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalUnclaimedRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRewards",
    data: BytesLike
  ): Result;

  events: {
    "LoyaltyRewardsDisabled()": EventFragment;
    "LoyaltyRewardsEnabled()": EventFragment;
    "UpdatedLoyaltyLevelRewardRate(uint256,uint256)": EventFragment;
    "UserLoyaltyRewardsEmitted(address,uint256,uint256)": EventFragment;
    "UserRewardClaimed(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LoyaltyRewardsDisabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoyaltyRewardsEnabled"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "UpdatedLoyaltyLevelRewardRate"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserLoyaltyRewardsEmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserRewardClaimed"): EventFragment;
}

export interface LoyaltyRewardsDisabledEventObject {}
export type LoyaltyRewardsDisabledEvent = TypedEvent<
  [],
  LoyaltyRewardsDisabledEventObject
>;

export type LoyaltyRewardsDisabledEventFilter =
  TypedEventFilter<LoyaltyRewardsDisabledEvent>;

export interface LoyaltyRewardsEnabledEventObject {}
export type LoyaltyRewardsEnabledEvent = TypedEvent<
  [],
  LoyaltyRewardsEnabledEventObject
>;

export type LoyaltyRewardsEnabledEventFilter =
  TypedEventFilter<LoyaltyRewardsEnabledEvent>;

export interface UpdatedLoyaltyLevelRewardRateEventObject {
  loyaltyLevel: BigNumber;
  rewardRate: BigNumber;
}
export type UpdatedLoyaltyLevelRewardRateEvent = TypedEvent<
  [BigNumber, BigNumber],
  UpdatedLoyaltyLevelRewardRateEventObject
>;

export type UpdatedLoyaltyLevelRewardRateEventFilter =
  TypedEventFilter<UpdatedLoyaltyLevelRewardRateEvent>;

export interface UserLoyaltyRewardsEmittedEventObject {
  user: string;
  epoch: BigNumber;
  rewardAmount: BigNumber;
}
export type UserLoyaltyRewardsEmittedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  UserLoyaltyRewardsEmittedEventObject
>;

export type UserLoyaltyRewardsEmittedEventFilter =
  TypedEventFilter<UserLoyaltyRewardsEmittedEvent>;

export interface UserRewardClaimedEventObject {
  user: string;
  rewardAmount: BigNumber;
}
export type UserRewardClaimedEvent = TypedEvent<
  [string, BigNumber],
  UserRewardClaimedEventObject
>;

export type UserRewardClaimedEventFilter =
  TypedEventFilter<UserRewardClaimedEvent>;

export interface IUserLoyaltyRewardsAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IUserLoyaltyRewardsAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimReward(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    doEmitRewards(overrides?: CallOverrides): Promise<[boolean]>;

    emitUserLoyaltyReward(
      user: string,
      epoch: BigNumberish,
      userLoyaltyLevel: BigNumberish,
      amountDeposited: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    emitUserLoyaltyRewardBatch(
      userRewardInputs: UserRewardInputStruct[],
      ksuTokenPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    loyaltyEpochRewardRates(
      loyaltyLevel: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    recoverERC20(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setDoEmitRewards(
      doEmitRewards_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setRewardRatesPerLoyaltyLevel(
      loyaltyEpochRewardRateInput: LoyaltyEpochRewardRateInputStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    totalUnclaimedRewards(overrides?: CallOverrides): Promise<[BigNumber]>;

    userRewards(user: string, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  claimReward(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  doEmitRewards(overrides?: CallOverrides): Promise<boolean>;

  emitUserLoyaltyReward(
    user: string,
    epoch: BigNumberish,
    userLoyaltyLevel: BigNumberish,
    amountDeposited: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  emitUserLoyaltyRewardBatch(
    userRewardInputs: UserRewardInputStruct[],
    ksuTokenPrice: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  loyaltyEpochRewardRates(
    loyaltyLevel: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  recoverERC20(
    tokenAddress: string,
    tokenAmount: BigNumberish,
    recipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setDoEmitRewards(
    doEmitRewards_: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setRewardRatesPerLoyaltyLevel(
    loyaltyEpochRewardRateInput: LoyaltyEpochRewardRateInputStruct[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  totalUnclaimedRewards(overrides?: CallOverrides): Promise<BigNumber>;

  userRewards(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    claimReward(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    doEmitRewards(overrides?: CallOverrides): Promise<boolean>;

    emitUserLoyaltyReward(
      user: string,
      epoch: BigNumberish,
      userLoyaltyLevel: BigNumberish,
      amountDeposited: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    emitUserLoyaltyRewardBatch(
      userRewardInputs: UserRewardInputStruct[],
      ksuTokenPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    loyaltyEpochRewardRates(
      loyaltyLevel: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recoverERC20(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDoEmitRewards(
      doEmitRewards_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setRewardRatesPerLoyaltyLevel(
      loyaltyEpochRewardRateInput: LoyaltyEpochRewardRateInputStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    totalUnclaimedRewards(overrides?: CallOverrides): Promise<BigNumber>;

    userRewards(user: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "LoyaltyRewardsDisabled()"(): LoyaltyRewardsDisabledEventFilter;
    LoyaltyRewardsDisabled(): LoyaltyRewardsDisabledEventFilter;

    "LoyaltyRewardsEnabled()"(): LoyaltyRewardsEnabledEventFilter;
    LoyaltyRewardsEnabled(): LoyaltyRewardsEnabledEventFilter;

    "UpdatedLoyaltyLevelRewardRate(uint256,uint256)"(
      loyaltyLevel?: BigNumberish | null,
      rewardRate?: null
    ): UpdatedLoyaltyLevelRewardRateEventFilter;
    UpdatedLoyaltyLevelRewardRate(
      loyaltyLevel?: BigNumberish | null,
      rewardRate?: null
    ): UpdatedLoyaltyLevelRewardRateEventFilter;

    "UserLoyaltyRewardsEmitted(address,uint256,uint256)"(
      user?: string | null,
      epoch?: BigNumberish | null,
      rewardAmount?: null
    ): UserLoyaltyRewardsEmittedEventFilter;
    UserLoyaltyRewardsEmitted(
      user?: string | null,
      epoch?: BigNumberish | null,
      rewardAmount?: null
    ): UserLoyaltyRewardsEmittedEventFilter;

    "UserRewardClaimed(address,uint256)"(
      user?: string | null,
      rewardAmount?: null
    ): UserRewardClaimedEventFilter;
    UserRewardClaimed(
      user?: string | null,
      rewardAmount?: null
    ): UserRewardClaimedEventFilter;
  };

  estimateGas: {
    claimReward(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    doEmitRewards(overrides?: CallOverrides): Promise<BigNumber>;

    emitUserLoyaltyReward(
      user: string,
      epoch: BigNumberish,
      userLoyaltyLevel: BigNumberish,
      amountDeposited: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    emitUserLoyaltyRewardBatch(
      userRewardInputs: UserRewardInputStruct[],
      ksuTokenPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    loyaltyEpochRewardRates(
      loyaltyLevel: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recoverERC20(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setDoEmitRewards(
      doEmitRewards_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setRewardRatesPerLoyaltyLevel(
      loyaltyEpochRewardRateInput: LoyaltyEpochRewardRateInputStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    totalUnclaimedRewards(overrides?: CallOverrides): Promise<BigNumber>;

    userRewards(user: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    claimReward(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    doEmitRewards(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    emitUserLoyaltyReward(
      user: string,
      epoch: BigNumberish,
      userLoyaltyLevel: BigNumberish,
      amountDeposited: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    emitUserLoyaltyRewardBatch(
      userRewardInputs: UserRewardInputStruct[],
      ksuTokenPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    loyaltyEpochRewardRates(
      loyaltyLevel: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recoverERC20(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setDoEmitRewards(
      doEmitRewards_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setRewardRatesPerLoyaltyLevel(
      loyaltyEpochRewardRateInput: LoyaltyEpochRewardRateInputStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    totalUnclaimedRewards(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userRewards(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
