/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFeeManagerAbi,
  IFeeManagerAbiInterface,
} from "../IFeeManagerAbi";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "lendingPoolAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "ecosystemFeeAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "protocolFeeAmount",
        type: "uint256",
      },
    ],
    name: "FeesEmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ProtocolFeesClaimed",
    type: "event",
  },
  {
    inputs: [],
    name: "claimProtocolFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "emitFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeManagerAbi__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeManagerAbiInterface {
    return new utils.Interface(_abi) as IFeeManagerAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeManagerAbi {
    return new Contract(address, _abi, signerOrProvider) as IFeeManagerAbi;
  }
}
