/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IKsuPriceAbi, IKsuPriceAbiInterface } from "../IKsuPriceAbi";

const _abi = [
  {
    inputs: [],
    name: "ksuTokenPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKsuPriceAbi__factory {
  static readonly abi = _abi;
  static createInterface(): IKsuPriceAbiInterface {
    return new utils.Interface(_abi) as IKsuPriceAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKsuPriceAbi {
    return new Contract(address, _abi, signerOrProvider) as IKsuPriceAbi;
  }
}
