/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUserLoyaltyRewardsAbi,
  IUserLoyaltyRewardsAbiInterface,
} from "../IUserLoyaltyRewardsAbi";

const _abi = [
  {
    inputs: [],
    name: "OnlyUserManager",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [],
    name: "LoyaltyRewardsDisabled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "LoyaltyRewardsEnabled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "loyaltyLevel",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardRate",
        type: "uint256",
      },
    ],
    name: "UpdatedLoyaltyLevelRewardRate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
    ],
    name: "UserLoyaltyRewardsEmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
    ],
    name: "UserRewardClaimed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "claimReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "doEmitRewards",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "userLoyaltyLevel",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountDeposited",
        type: "uint256",
      },
    ],
    name: "emitUserLoyaltyReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "user",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "epoch",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "userLoyaltyLevel",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountDeposited",
            type: "uint256",
          },
        ],
        internalType: "struct UserRewardInput[]",
        name: "userRewardInputs",
        type: "tuple[]",
      },
      {
        internalType: "uint256",
        name: "ksuTokenPrice",
        type: "uint256",
      },
    ],
    name: "emitUserLoyaltyRewardBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loyaltyLevel",
        type: "uint256",
      },
    ],
    name: "loyaltyEpochRewardRates",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "recoverERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "doEmitRewards_",
        type: "bool",
      },
    ],
    name: "setDoEmitRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "loyaltyLevel",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "epochRewardRate",
            type: "uint256",
          },
        ],
        internalType: "struct LoyaltyEpochRewardRateInput[]",
        name: "loyaltyEpochRewardRateInput",
        type: "tuple[]",
      },
    ],
    name: "setRewardRatesPerLoyaltyLevel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalUnclaimedRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "userRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IUserLoyaltyRewardsAbi__factory {
  static readonly abi = _abi;
  static createInterface(): IUserLoyaltyRewardsAbiInterface {
    return new utils.Interface(_abi) as IUserLoyaltyRewardsAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUserLoyaltyRewardsAbi {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IUserLoyaltyRewardsAbi;
  }
}
